### ISSUE TITLE
运行完train或者predict没有反应

### ISSUE THREAD

**Issue by jasonpan777** [yanwii/ChinsesNER-pytorch#12]
![image](https://user-images.githubusercontent.com/41572707/202890213-644a9535-4a30-47ec-b6a5-64b278265278.png)
你好，我这里输入完指令也不报错，但是没有反应，请问怎么办

**Comment by SuperBruceJia** [comment]
是在Anaconda Prompt上执行的吗？

**Comment by yanwii** [comment]
建议单步调试一下，看哪里出了问题。
________________________________
发件人: Shuyue Jia ***@***.***>
发送时间: 2022年11月23日 12:20
收件人: yanwii/ChinsesNER-pytorch ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [yanwii/ChinsesNER-pytorch] 运行完train或者predict没有反应 (Issue #12)


是用Anaconda Prompt执行的吗？

―
