### ISSUE TITLE
这个是怎么回事啊大佬

### ISSUE THREAD

**Issue by chosen-boy** [yanwii/ChinsesNER-pytorch#13]
![image](https://github.com/yanwii/ChinsesNER-pytorch/assets/95687624/06a33e4a-40a7-45d9-a3d1-e0a232e42971)

**Comment by yanwii** [comment]
https://github.com/yanwii/ChinsesNER-pytorch/blob/3a04353a835e4e2825cf5cafef9375e96e036462/main.py#L61
这里会加载配置文件中的tags，看看是不是没有配置

**Comment by chosen-boy** [comment]
![image](https://github.com/yanwii/ChinsesNER-pytorch/assets/95687624/47353f18-0c6f-43f7-8a6b-0f6f089ed091)
这里不是已经配置好了吗

**Comment by yanwii** [comment]
tags

**Comment by chosen-boy** [comment]
咋配置啊，填了报错
![image](https://github.com/yanwii/ChinsesNER-pytorch/assets/95687624/8abb7435-6273-43f4-a141-37fea3ce93a0)

**Comment by yanwii** [comment]
单词拼错了，大哥
