### ISSUE TITLE
关于数据处理的问题

### ISSUE THREAD

**Issue by striderdu** [yanwii/ChinsesNER-pytorch#2]
想知道 START、STOP 这些 tag 的用途是什么，更换数据集时 model.py 是不是也要做修改

**Comment by yanwii** [comment]
START和STOP提供开始和结束标签
当需要添加 删除或修改标签时,可以在配置文件中操作
https://github.com/yanwii/ChinsesNER-pytorch/blob/b0af634abaa68cd4a224f1c168e64f9cf1d5493a/models/config.yml#L6

**Comment by striderdu** [comment]
还是不太明白。什么叫开始和结束标签？和B、E标签是等价的吗？如果使用BIEOS标注方法，
https://github.com/yanwii/ChinsesNER-pytorch/blob/b0af634abaa68cd4a224f1c168e64f9cf1d5493a/model.py#L14
这里是不是要做修改？

**Comment by yanwii** [comment]
START和STOP是程序内置的标签，这个不用管，不管用什么标注方法，START和STOP都存在，你只需要做的就是进行BIEOS标注就行了

**Comment by striderdu** [comment]
好的，了解了，感谢你的解答！
